baseURL = "https://www.magiccityconnector.org/"
languageCode = "en-us"
title = "Magic City Connector"
theme = "mgc"

###################################### Navigation ######################################
[menu]

        [[menu.main]]
        name = "home"
        url = "/"
        weight = 1

        [[menu.main]]
        name = "news"
        identifier = "news"
        url = "/posts"
        weight = 2

        [[menu.main]]
        name = "details"
        identifier = "details"
        url = "/details/why"
        weight = 3

        [[menu.details]]
        name = "why"
        url = "/details/why"
        weight = 1

        [[menu.details]]
        name = "where"
        url = "/details/where"
        weight = 2

